### ISSUE TITLE
Bring in civic apps project templates

### ISSUE THREAD

**Issue by fungjj92** [azavea/pwd-fishway#1]
Set up the project basics.

The project will likely be an IIS hosted site, similar to https://github.com/azavea/pwd-river-dispatches, but preparing the project for that format will come later.

- [x] Issue template
- [x] PR template
- [x] CA app template
- [x] Change project ports
- [x] Update README with setup instructions accordingly

Should be able to serve the react app.

**Comment by kellyi** [comment]
We should consider making some upgrades to the app template as part of this work. The Babel configuration is one step behind the config in Create-React-App-generated apps like OAR and ISM, and we've discussed wanting to have the prettier-webpack-plugin -- https://www.npmjs.com/package/prettier-webpack-plugin -- available to do automatic code formatting on file saves, too. (For the latter we could adopt the prettierrc file used in ISM).
