### ISSUE TITLE
Style and implement Button component

### ISSUE THREAD

**Issue by alexelash** [azavea/pwd-fishway#49]
# Overview
Using Rebass button structure, create button styles that we will need for the app:
- [x] Primary
- [x] Secondary
- [x] Icon button

<img width="450" alt="Screen Shot 2019-05-02 at 11 55 56 AM" src="https://user-images.githubusercontent.com/5672295/57088932-56b24880-6cd1-11e9-9e6e-6e6c9a687097.png">
<img width="73" alt="Screen Shot 2019-05-02 at 11 56 04 AM" src="https://user-images.githubusercontent.com/5672295/57088933-56b24880-6cd1-11e9-831a-16aa1492fcbf.png">
<img width="52" alt="Screen Shot 2019-05-02 at 11 56 14 AM" src="https://user-images.githubusercontent.com/5672295/57088934-56b24880-6cd1-11e9-8d8c-25426f902755.png">

## Describe the solution you'd like
- [ ] Add single button component with appropriate props to change out the style
- [ ] Replace app instances of buttons with the new Button component.

**Comment by fungjj92** [comment]
Looks complete! Closing.
