### ISSUE TITLE
Pin yarn package versions before prod deploy

### ISSUE THREAD

**Issue by fungjj92** [azavea/pwd-fishway#54]
## Overview

This app will live in the museum without development updates for years. There _shouldn't_ be complications however for good measure, pin all versions of the yarn packages before the production deploy.

**Comment by caseycesari** [comment]
It might be worth looking into https://docs.npmjs.com/cli/ci.html for building the project. I haven't used it, but it appears to be better for getting reproducible builds.

**Comment by fungjj92** [comment]
Shares point with #114

**Comment by fungjj92** [comment]
No longer doing.
