### ISSUE TITLE
Create animated background component

### ISSUE THREAD

**Issue by alexelash** [azavea/pwd-fishway#66]
The background of the app will have animated bubbles and change its color (and some content) depending on which page of the app the user is in. This issue includes creating the component and making it work on page change using [React Transition Group](https://github.com/reactjs/react-transition-group).

Top
![Screen Shot 2019-05-14 at 9 50 39 AM](https://user-images.githubusercontent.com/5672295/57703299-c7405a00-762d-11e9-856c-184d5269aae0.png)

Bottom
![Screen Shot 2019-05-14 at 9 50 46 AM](https://user-images.githubusercontent.com/5672295/57703301-c7d8f080-762d-11e9-8505-bd5c55e932aa.png)

**Comment by fungjj92** [comment]
The animated background is complete and looks great 👍 Bubble are left, and captured in #88. Gonna close this.
