### ISSUE TITLE
Style navigation bar

### ISSUE THREAD

**Issue by alexelash** [azavea/pwd-fishway#67]
- [x] Add icons
- [x] Style text & containing component
- [x] Add `:active` state
- [x] Add `.current` state

![Screen Shot 2019-05-14 at 9 53 28 AM](https://user-images.githubusercontent.com/5672295/57703470-269e6a00-762e-11e9-9e2e-1841aad6e682.png)

**Comment by fungjj92** [comment]
Looks so good! From demo I have some feedback -- in the Quiz tab, the navbar text is white overlaying a very light blue. The text is a little hard to read. What can we do there?

**Comment by alexelash** [comment]
Thanks! I decided to punt handling the light text over light blue to this issue: https://github.com/azavea/pwd-fishway/issues/83, since I haven't handled animating the nav bar in general yet.

It'll look more like this once that issue gets tackled:
<img width="1325" alt="Screen Shot 2019-05-30 at 2 51 21 PM" src="https://user-images.githubusercontent.com/5672295/58656516-69c53200-82ea-11e9-91ef-a35fc50e0cc3.png">

**Comment by fungjj92** [comment]
Coolio :) Just making sure the comment wasn't lost
