### ISSUE TITLE
Design support blackbox

### ISSUE THREAD

**Issue by fungjj92** [azavea/pwd-fishway#75]
Because development and design are happening quite simultaneously, cross-pollination and support time arises naturally. Account for this time in sprint planning

**Comment by maurizi** [comment]
Spent time pairing with @alexelash on #87, 1 point

**Comment by fungjj92** [comment]
Reset to 1 point for the sprint 5/31-6/13

**Comment by fungjj92** [comment]
0 points remaining. Spent on react modal scroll and anchors, react transitions.

**Comment by fungjj92** [comment]
1 point spent on design support for Lottie medallion on Quiz. 0 points left for sprint ending 8/8/19

**Comment by fungjj92** [comment]
Reset to 2 points for sprint starting 8/8

**Comment by fungjj92** [comment]
Reset to 1 point starting 8/22
