### ISSUE TITLE
Create navbar component

### ISSUE THREAD

**Issue by fungjj92** [azavea/pwd-fishway#8]
## Overview

The app will have a navbar present on all screens except the screensaver. 

The wireframes copy and style are still in flux, don't try to style them meticulously. Don't worry about colors. Ask design to pull the icons from FontAwesome, or ignore them for now.

### Describe the solution you'd like

Add the screensaver component as per the wireframes, but clicking the tabs won't do anything yet.

![image](https://user-images.githubusercontent.com/10568752/56225546-988b8f80-603f-11e9-93df-b5ad0641d257.png)
https://share.goabstract.com/b2d6b222-7a48-4e60-af3b-527deea41354

**Comment by kellyi** [comment]
Consider setting up react-router-dom as part of this work and using it to handle storing and updating the application's routing state.

**Comment by fungjj92** [comment]
@alexelash would like to have interaction between tabs, which on initial research is more flexible when transitioning between components at the same route. So, at least for now, everything will be at `/`
