### ISSUE TITLE
App is not showing screensaver after being idle

### ISSUE THREAD

**Issue by maurizi** [azavea/pwd-fishway#86]
## Overview

The application is supposed to show the screensaver after a certain amount of time, but does not. This was working previously.

### Expected Behavior

After loading the application and clicking to go from the screensaver to the main application, the screensaver should load after a specified time (currently 10 seconds), provided that no videos are currently playing.

### Actual Behavior

The screensaver is never shown.

### Steps to Reproduce

* Go to https://staging-pwd-fishway.netlify.com/
* Click anywhere on the screen to enter the application
* Click on the video to pause it, and wait 10 seconds

**Comment by fungjj92** [comment]
The idle time constant was updated to 100000000ms or 1666 minutes, I tested locally with 5000ms and the idle timer works. Phew 😅

**Comment by fungjj92** [comment]
Update the constant to a minute (or two ?) and perhaps we can add the comment `//should be 10000ms` or whatever time, for when we inevitably fuss with the constant during development.

0 points if rolled into another card since it's such a small change.
