### ISSUE TITLE
Style pass: About tab

### ISSUE THREAD

**Issue by alexelash** [azavea/pwd-fishway#92]
<img width="1326" alt="Screen Shot 2019-05-30 at 2 49 22 PM" src="https://user-images.githubusercontent.com/5672295/58656671-bad52600-82ea-11e9-8f85-f47edaf25b27.png">

- [x] Style dots
- [x] Style text
- [x] Fixup placement of page title
- [x] Set off-screen slides to lower opacity

**Comment by fungjj92** [comment]
About tab looks complete! Can this be closed?
